microbit num1 = input("\nEnter first number: ")
num2 = input("\nEnter second number: ")
sum = float(num1) + float(num2)
sub = float(num1) - float(num2)
mul = float(num1) * float(num2)
div = float(num1) / float(num2)
rem = float(num1) % float(num2)
print("\nAddition of {0} & {1} = {2}".format(num1,num2,sum))
print("\nSubtraction of {0} & {1} = {2}".format(num1,num2,sub))
print("\nMultiplication of {0} & {1} = {2}".format(num1,num2,mul))
print("\nDivision of {0} & {1} = {2}".format(num1,num2,div))
print("\nRemainder of {0} & {1} = {2}".format(num1,num2,rem))

print("\nEnding Program")
